Add methods for process inside controller
adonisjs/docs pull request #324
Opened 2018-10-28 18:34 UTC by ahmetanbar

2018-10-29 13:04 UTC, thetutlage requested changes

2018-10-29 13:04 UTC, thetutlage commented on 06-Digging-Deeper/03-File-Uploads.adoc
> +            body[name] = value;
Can you please fix the indentation here? It's must be 2 spaces

2018-10-29 13:04 UTC, thetutlage commented on 06-Digging-Deeper/03-File-Uploads.adoc
> +            body[name] = value;
Also where does the `body` object comes from?

2018-10-29 13:04 UTC, thetutlage commented on 06-Digging-Deeper/03-File-Uploads.adoc
> +    .field((name, value) => {
Same here, badly formatted and where is the `body` object coming from?

2018-11-01 08:35 UTC, thetutlage commented
Your code examples are still inconsistent with what we have already have in our examples. For example: we do not use `;` at the end.

Can you please check and format it properly?

2018-12-18 08:30 UTC, RomainLanz commented
Any update @ahmetanbar?

2018-12-22 05:15 UTC, thetutlage approved these changes

2018-12-22 05:15 UTC, closed without merging