Grammatical Tweaks (Section 05)
adonisjs/docs pull request #328
Opened 2018-12-17 07:46 UTC by furey

Following https://github.com/adonisjs/docs/pull/314, this PR applies numerous grammatical tweaks to the "05-Security" section of the documentation.

2018-12-17 10:02 UTC, RomainLanz requested changes
Wow! Thanks again for this PR @furey! 😍 

I believe we can also add a link to [Adonis Persona](https://github.com/adonisjs/adonis-persona) in the authentication section as a `note` or `tips`.

2018-12-17 10:02 UTC, RomainLanz commented on 05-Security/02-Authentication.adoc
> +Using authenticators you can build traditional *session based* login systems and secure your *REST APIs*.
We should remove the term `REST` here.
```suggestion

Using authenticators you can build traditional *session based* login systems and secure your *APIs*.
```

2018-12-17 10:02 UTC, RomainLanz commented on 05-Security/01-Getting-Started.adoc
> +As HTML forms are only capable of making `GET` and `POST` requests, you cannot use HTTP verbs like `PUT` or `DELETE` to perform RESTful operations via a form's `method` attribute.
Let's remove the `REST` term here.

```suggestion
As HTML forms are only capable of making `GET` and `POST` requests, you cannot use HTTP verbs like `PUT` or `DELETE` to perform resourceful operations via a form's `method` attribute.
```

2018-12-17 10:02 UTC, RomainLanz commented on 05-Security/02-Authentication.adoc
> +*Stateless* authentication requires the user to resend their credentials on each HTTP request, which is very common with REST APIs.
Also here 

```suggestion
*Stateless* authentication requires the user to resend their credentials on each HTTP request, which is very common with APIs.
```

2018-12-17 10:02 UTC, RomainLanz commented on 05-Security/02-Authentication.adoc
> +  async login ({ request, auth, response }) {
There's no need to extract the `response` from the context here.
Also, could be good to keep them in the alphabetical order.

```suggestion
  async login ({ auth, request }) {
```

2018-12-18 03:46 UTC, furey commented
> I believe we can also add a link to Adonis Persona in the authentication section as a note or tips.

✅ https://github.com/adonisjs/docs/pull/328/commits/7b6a76bc53250cc1e01081259eeec5d9a5dd611b

2018-12-18 03:52 UTC, furey reviewed
> Wow! Thanks again for this PR @furey! 😍

No worries!

2018-12-18 08:29 UTC, RomainLanz approved these changes

2018-12-22 02:37 UTC, furey commented
Hi @RomainLanz & @thetutlage,

I'd finished parsing the "06-Digging-Deeper" section of the documentation, so thought I'd update this PR with those files while still waiting for approval/merge.

Cheers!

2018-12-22 05:14 UTC, thetutlage commented
@furey Do you want us to wait for the other changes, or should I go ahead and merge it right now and you will do a different PR for rest of the changes?

2018-12-22 11:06 UTC, furey commented
@thetutlage Happy for you to merge now and I'll submit a different PR for the rest. Thanks! 👍

2018-12-22 12:36 UTC, merged

2018-12-22 12:36 UTC, RomainLanz commented
Thanks a lot!